properties([parameters([[$class: 'ChoiceParameter', choiceType: 'PT_SINGLE_SELECT', filterLength: 1, filterable: false, name: 'RUNNING_ENVIRONMENT', randomName: 'choice-parameter-97273372558868', script: [$class: 'GroovyScript', fallbackScript: [classpath: [], sandbox: false, script: ''], script: [classpath: [], sandbox: false, script: '''return[
\'Development\',
\'Staging\', 
\'Live\'
]''']]], [$class: 'CascadeChoiceParameter', choiceType: 'PT_SINGLE_SELECT', filterLength: 1, filterable: false, name: 'PROJECT', randomName: 'choice-parameter-97273375655194', referencedParameters: 'RUNNING_ENVIRONMENT', script: [$class: 'GroovyScript', fallbackScript: [classpath: [], sandbox: false, script: ''], script: [classpath: [], sandbox: false, script: '''if (RUNNING_ENVIRONMENT.equals("Development")){
    return["language1", "language2", "language3"]
}
else if(RUNNING_ENVIRONMENT.equals("Staging")){
    return["languageA", "languageB", "languageC"]
}
else if(RUNNING_ENVIRONMENT.equals("Live")){
    return["languageP1", "languageP2", "languageP2", "languageP3"]
}''']]]])])

pipeline{
    agent any
    stages{
        stage('setup parameters') {
            
        }
    }
}